version: "3.7"
   
services:
    db:
        image: "mcr.microsoft.com/mssql/server"
        user: root
        volumes:
            - mssql_data:/var/opt/mssql/data
        environment:
            SA_PASSWORD: "Docker1!"
            ACCEPT_EULA: "Y"
    app:
        build: .
        volumes: 
            - .:/app
        ports:
            - "8080:80"
        depends_on:
            - db

volumes:
    mssql_data: