-- Create users table
CREATE TABLE users
(
	id INT NOT NULL PRIMARY KEY IDENTITY,
	username NVARCHAR(40) NOT NULL,
	email NVARCHAR(100) NOT NULL,
	password NVARCHAR(200) NOT NULL,
	age INT NOT NULL,
	is_robot BIT
)

-- Get list of tables in the db
SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'BASE TABLE';